stages:
  - build
  - test
  - dockerize

variables:
  JACOCO_CSV_LOCATION: '$CI_PROJECT_DIR/smart-home-service/build/jacocoCsv'

build:
  stage: build
  image: inf-docker.fh-rosenheim.de/studwinten4338/docker-images/gradle:6.8.3-jdk11
  script:
    - echo "Compiling"
    - gradle assemble
  artifacts:
    paths:
      - ./build/libs/*.jar
    expire_in: 1 day

test:
  stage: test
  image: inf-docker.fh-rosenheim.de/studwinten4338/docker-images/gradle:6.8.3-jdk11
  script:
    - echo "Running unit tests and static code analysis"
    - gradle test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_CSV_LOCATION
  artifacts:
    reports:
      junit:
        - ./smart-home-service/build/test-results/test/TEST-*.xml
    paths:
      - ./smart-home-service/build*
    expire_in: 1 day

dockerize:
  stage: dockerize
  image: inf-docker.fh-rosenheim.de/studwinten4338/docker-images/docker:latest #gradle:6.8.3-jdk11
  script:
    - echo "Dockerization"
    - gradle dockerBuildImage