stages:
    - build
    - test

build:
    stage: build
    image: gradle:6.8.3-jdk11
    script:
        - echo "Compiling"
        - gradle build
    artifacts:
        paths:
            - ./build/libs/*.jar
        expire_in: 1 week

test:
    stage: test
    image: adoptopenjdk:11-jre-hotspot
    script:
        - echo "Testing"
        - cd ./build/libs
        - java jar *.jar
